name: Environments secrets env action workflow  
on: push

jobs:  
  
  test:
    runs-on: ubuntu-latest  
    environment: testing 
    env:
        DB_NAME:   ${{ secrets.DB_NAME }}  
        DB_PORT:   ${{ vars.DB_PORT }} 
    steps: 
        - name: Run Environments secrets env
          run: |  
              echo testing DB_NAME =   "${{env.DB_NAME}}"
              echo testing DB_PORT =   "${{env.DB_PORT}}"
  
  
  prod:
    runs-on: ubuntu-latest  
    environment: prod 
    env:
        DB_NAME:   ${{ secrets.DB_NAME }}  
        DB_PORT:   ${{ vars.DB_PORT }} 
    steps: 
        - name: Run Environments secrets env
          run: |  
              echo prod DB_NAME =   "${{env.DB_NAME}}"
              echo prod DB_PORT =   "${{env.DB_PORT}}"